### ISSUE TITLE
Cant import embed_video

### ISSUE THREAD

**Issue by Grce47** [Grce47/Django-ML-Internship#1]
videos\model.py -> from embed_video.fields import EmbedVideoField

- [x] Added to INSTALLED APPS
- [x] Installed django-embed-video

Still not working :(
![Screenshot (171)](https://user-images.githubusercontent.com/77105126/167290593-bb165412-cdab-4145-9481-e9b4384fc5b5.png)

@Ammetre

**Comment by Ammetre** [comment]
Issue closed: the database is changed with the commit "Bugfix #1;"

**Comment by Grce47** [comment]
- Code Error: add default link to EmbedVideoField(default="<default-link>")
- VS Code Error: select correct python interpreter
